### ISSUE TITLE
Example read_dfs2: grid cell coordinates created as integer

### ISSUE THREAD

**Issue by LAGO-Support** [DHI/DHI-MATLAB-Toolbox#1]
In lines
x = saxis.X0 + saxis.Dx*(0.5+(0:(saxis.XCount-1)))';
y = saxis.Y0 + saxis.Dy*(0.5+(0:(saxis.YCount-1)))';

One solution may be
x = saxis.X0 + saxis.Dx*(0.5+double(0:(saxis.XCount-1)))';
y = saxis.Y0 + saxis.Dy*(0.5+double(0:(saxis.YCount-1)))';

**Comment by LAGO-Support** [comment]
Another potential issue in the same lines is starting at 0.5. By using a dfs2 and a point shape file in the same UTM projection, the dfs2 editor view suggest that 0.5 should be removed. If I am not mistaken, the lines should be modified to
x = saxis.X0 + saxis.Dx*(double(0:(saxis.XCount-1)))';
y = saxis.Y0 + saxis.Dy*(double(0:(saxis.YCount-1)))';

**Comment by JesperGr** [comment]
About the second issue of 0.5: The value in a dfs2 file belongs in the center of the grid cells, i.e. from i*dx to (i+1)*dx and similar for y, the value kind of fills out that entire cell. That is not the way a wireplot works in MATLAB: In a wireplot values belong on the grid line junctions. 

By adding 0.5, this moves the grid in MATLAB to the center of the DFS2 grid cells, and makes a plot of the center of the cells.  Hence, the 0.5 needs to be there.
