### ISSUE TITLE
read_dfsu_2D.m

### ISSUE THREAD

**Issue by Krys1202** [DHI/DHI-MATLAB-Toolbox#2]
Hi,
I'm using Mike21FM.
I would like to separate ebb and flood for current speed in my domain.
I've the index (timesteps) for ebb and flood, but I didn't manage to calculate node values for each timestep flood and for each timestep ebb...  

I tried "for i=index_Ebb" instead of "for i=0:nsteps-1"
CSpeedF = double(dfsu2.ReadItemTimeStep(7,i).Data)';
 but I obtained : No method 'ReadItemTimeStep' with matching signature found for class 'DHI.Generic.MikeZero.DFS.dfsu.DfsuFile'.

Then I tested this : CSpeedF=readItemTimestep(dfsu2,7,[5,7,10]);
No appropriate method, property, or field 'TSO' for class 'DHI.Generic.MikeZero.DFS.dfsu.DfsuFile'.

Could you tell me where I'm wrong please?

Thanks!

**Comment by JesperGr** [comment]
Is this still a problem? Can you please provide a bit more code to show what you are doing?

Thank you.
