### ISSUE TITLE
Error using NETaddAssembly

### ISSUE THREAD

**Issue by madsroge90** [DHI/DHI-MATLAB-Toolbox#4]
Hi, 

When running the example "read_dfsu_3D.m" i get the following error:
I am running MIKE 2021 and MATLAB 2020b

Error using NETaddAssembly (line 32)
'MatlabDfsUtil.dll' could not be found in the .NET Global Assembly Cache (GAC).

Error in NETaddDfsUtil (line 2)
    DfsUtilAss = NETaddAssembly('MatlabDfsUtil.dll');

Error in mzNetFromElmtArray (line 23)
H = NETaddDfsUtil();

Error in read_dfsu_3D (line 27)
tn3D = mzNetFromElmtArray(dfsu3.ElementTable);

I have no problems running other examples. Can you help me with solving this error?

Best
Regards,
Mads

**Comment by JesperGr** [comment]
Can you check if the MatlabDfsUtil.dll file exists inside the mbin folder, or one of its subfolders?

**Comment by madsroge90** [comment]
The file is located in the mbin folder. I expect it to be caused by using the newest version of Matlab 2020b?

**Comment by JesperGr** [comment]
I would not know if something has changed for MATLAB 2020b.

What happens if you use the internal MATLAB function for loading assemblies, i.e. something like:

asmInfo = NET.addAssembly('c:\path-to-toolbox\mbin\MatlabDfsUtil.dll')

?

A bit more info on that method is here:

https://www.mathworks.com/help/matlab/ref/net.addassembly.html

**Comment by madsroge90** [comment]
Hi Jesper,

If I add the following to the function "H = NETaddDfsUtil(dfsAssemblyName)", it will work again. 

DfsUtilAss = NET.addAssembly('C:\path-to-toolbox\mbin\MatlabDfsUtil.dll')

Maybe this file should be added like this, but the script should find its relative path by it self.

Best regards,
Mads

**Comment by JesperGr** [comment]
That is what the NETaddAssembly method should take care of. 

Have you called 
```
addpath(genpath('C:\Matlab\mbin'));
```
? 

I believe that is required before the NETaddAssembly will work.

**Comment by madsroge90** [comment]
I have now removed the fix I did last time, and it still works.... So maybe the fix I did last time added something permanently??

**Comment by JesperGr** [comment]
OK, so nothing wrong with the code, but maybe with the installation instructions. I will close this for now.
